### ISSUE TITLE
No module named 'zigate'

### ISSUE THREAD

**Issue by Math43** [doudz/homeassistant-zigate#107]
Bonjour, au démarrage de HA (installé dans un container docker), j'ai le message suivant dans les logs:

`2020-03-03 10:08:35 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.zigate. Make sure all dependencies are installed
home-assistant   | Traceback (most recent call last):
home-assistant   |   File "/usr/src/homeassistant/homeassistant/loader.py", line 391, in _load_file
home-assistant   |     module = importlib.import_module(path)
home-assistant   |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
home-assistant   |     return _bootstrap._gcd_import(name[level:], package, level)
home-assistant   |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
home-assistant   |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
home-assistant   |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
home-assistant   |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
home-assistant   |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
home-assistant   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
home-assistant   |   File "/config/custom_components/zigate/__init__.py", line 13, in <module>
home-assistant   |     import zigate
home-assistant   | ModuleNotFoundError: No module named 'zigate'
home-assistant   | 2020-03-03 10:08:35 ERROR (MainThread) [homeassistant.components.homeassistant] Component error: zigate - Integration 'zigate' not found.
home-assistant   | 2020-03-03 10:18:15 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.zigate. Make sure all dependencies are installed`

qu'est ce qui pourrait manquer ?

**Comment by dumoulinjb** [comment]
Bonjour,
J'ai également ce problème avec une installation sur raspberry pi via git clone.
C'est le premier composant custom que j'essaie d'installer.
