### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by vini59fr** [doudz/homeassistant-zigate#129]
Hello

Zigate Admin bug chez moi sur certaines fonction (quasiement tous les boutons d'acrion : Permit Join, Led ON/OFF, Discover) : 500 Internal Server Error
![2020-08-13 17_24_44-Window](https://user-images.githubusercontent.com/65531566/90154440-6c466700-dd8a-11ea-8ef8-9e4973023a95.png)

![2020-08-13 17_25_01-Window](https://user-images.githubusercontent.com/65531566/90154496-7b2d1980-dd8a-11ea-8e77-3464e7343efb.png)

Home Assistant 0.114.0
host_os | HassOS 4.12
Zigate à jour : 540958e

**Comment by vini59fr** [comment]
En log ca donne ca : 

Error handling request
17:34:15 – custom_components/zigate/adminpanel.py (ERROR)



Logger: aiohttp.server
Source: custom_components/zigate/adminpanel.py:35
First occurred: 17:34:15 (1 occurrences)
Last logged: 17:34:15

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 964, in _create_direct_connection
    hosts = await asyncio.shield(self._resolve_host(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 829, in _resolve_host
    addrs = await \
  File "/usr/local/lib/python3.8/site-packages/aiohttp/resolver.py", line 29, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/config/custom_components/zigate/adminpanel.py", line 20, in get
    return await self._handle_request("GET", request, requested_url)
  File "/config/custom_components/zigate/adminpanel.py", line 35, in _handle_request
    async with aiohttp.request(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1051, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 971, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host homeassistant.local:8123 ssl:default [Name does not resolve]

**Comment by doudz** [comment]
il est peut-être nécessaire de définir l'URL externe et interne dans Configuration => Général

**Comment by vini59fr** [comment]
> il est peut-être nécessaire de définir l'URL externe et interne dans Configuration => Général

Bon, c'était bien ça le problème 
L'adresse de l'URL interne n'etait plus la bonne

Désolé pour l'ouverture d'une issue inutile
