### ISSUE TITLE
Pizigate : Probleme flash firmware 3.1d

### ISSUE THREAD

**Issue by vini59fr** [doudz/homeassistant-zigate#147]
Bonjour

Je tente en vain de faire la mise à jour du firmware en 3.1d, de mon Pizigate

je lance le service zigate.upgrade_firmware, le backup du firmware existant se fait bien. HA m'affiche "deconnexion" et puis plus rien.
Obligé d'eteindre electriquement mon Pi.
Quand ca redemarre, le firmware est toujours en 3.1c

Je n'avais pas eu de probleme pour le flash en 3.1c avec ce systeme.

j'ai ces 2 lignes d'erreur dans home-assistant.log

2020-10-27 12:19:50 ERROR (SyncWorker_31) [ZiGate Flasher] Unpack failed, length: 0, msg
NoneType: None
2020-10-27 12:19:50 ERROR (SyncWorker_31) [ZiGate Flasher] Change baudrate failed
NoneType: None

**Comment by doudz** [comment]
Est-ce que tu utilises bien la dernière version ?
Si le backup se fait alors ça fonctionne déjà à moitié

> HA m'affiche "deconnexion" 

C'est à dire ? HA n'est pas supposé s'arrêter 

> Obligé d'eteindre electriquement mon Pi.

Et le système encore moins

**Comment by vini59fr** [comment]
Derniere version Oui
![2020-10-28 09_04_00-Zigate Admin - Home Assistant](https://user-images.githubusercontent.com/65531566/97408578-9379f280-18fc-11eb-9fd3-73ab14e2c38d.png)

J'ai bien la notification que le backup est créé mais HA plante et plus rien ne fonctionne, obligé de redemarrer electriquement
![2020-10-28 09_06_19-Window](https://user-images.githubusercontent.com/65531566/97409076-5b26e400-18fd-11eb-8b44-18f9abd081c7.png)



Je viens de tester à l'instant et j'ai ca en log : 
2020-10-28 09:06:11 INFO (SyncWorker_40) [zigate] Download latest firmware
2020-10-28 09:06:11 INFO (SyncWorker_40) [zigate] Searching for ZiGate firmware
2020-10-28 09:06:11 INFO (SyncWorker_40) [zigate] Found ZiGate_v3.1d.bin
2020-10-28 09:06:11 INFO (SyncWorker_40) [zigate] Found ZiGate_v3.1c.bin
2020-10-28 09:06:11 INFO (SyncWorker_40) [zigate] Found ZiGate_v3.1b.bin
2020-10-28 09:06:11 INFO (SyncWorker_40) [zigate] Found ZiGate_Coordinator_v3.1a.bin
2020-10-28 09:06:11 INFO (SyncWorker_40) [zigate] Found ZiGate_v30f.bin
2020-10-28 09:06:11 INFO (SyncWorker_40) [zigate] Found ZiGate_3.0f_pre_release.bin
2020-10-28 09:06:11 INFO (SyncWorker_40) [zigate] Latest is ZiGate_v3.1d.bin
2020-10-28 09:06:11 INFO (SyncWorker_40) [zigate] Downloading https://github.com/fairecasoimeme/ZiGate/releases/download/v3.1d/ZiGate_v3.1d.bin to /tmp
2020-10-28 09:06:12 INFO (SyncWorker_40) [zigate] Done
2020-10-28 09:06:17 ERROR (SyncWorker_40) [ZiGate Flasher] Unpack failed, length: 0, msg 
NoneType: None
2020-10-28 09:06:17 ERROR (SyncWorker_40) [ZiGate Flasher] Change baudrate failed
NoneType: None
2020-10-28 09:07:57 ERROR (zeroconf-ServiceBrowser__miio._udp.local.-_ipps._tcp.local.-_dkapi._tcp.local.-_axis-video._tcp.local.-_nut._tcp.local.-_googlecast._tcp.local.-_Volumio._tcp.local.-_elg._tcp.local.-_plugwise._tcp.local.-_bond._tcp.local.-_ipp._tcp.local.-_http._tcp.local.-_esphomelib._tcp.local.-_printer._tcp.local.-_api._udp.local.-_hap._tcp.local.-_spotify-connect._tcp.local.-_viziocast._tcp.local.-_ssh._tcp.local.-_wled._tcp.local.-_xbmc-jsonrpc-h._tcp.local.-_daap._tcp.local.-_homekit._tcp.local._309) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1721, in run
    self._service_state_changed.fire(
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1479, in fire
    h(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/zeroconf/__init__.py", line 304, in service_update
    hass.add_job(
  File "/usr/src/homeassistant/homeassistant/core.py", line 292, in add_job
    self.loop.call_soon_threadsafe(self.async_add_job, target, *args)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 764, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by doudz** [comment]
fixed
