### ISSUE TITLE
Capteur de temperature

### ISSUE THREAD

**Issue by orrionis** [doudz/homeassistant-zigate#152]
Bonjours a tous

Voila je viens d'avoir un capteur de température
il est bien découvert par le plugin, mais seul celui d'humidité est bien lue.

pour info voici mes log

> 2020-11-12 17:19:59 DEBUG (Thread-6) [zigate] REQUEST : 0x0049 FFFC3C00
2020-11-12 17:19:59 DEBUG (Thread-6) [zigate] Msg to send b'0049000472fffc3c00'
2020-11-12 17:19:59 DEBUG (Thread-6) [zigate] Encoded Msg to send b'010210490210021472fffc3c021003'
2020-11-12 17:19:59 DEBUG (Thread-6) [zigate] Waiting for status message for command 0x0049
2020-11-12 17:19:59 DEBUG (ZiGate-Listen) [zigate] Raw packet received, b'\x01\x80\x02\x10\x02\x10\x02\x15\\\x02\x10\x90\x02\x10I\x02\x10\x03'
2020-11-12 17:19:59 DEBUG (ZiGate-Event Loop) [zigate] Dispatch ZIGATE_PACKET_RECEIVED
2020-11-12 17:19:59 DEBUG (ZiGate-Decode data) [zigate] Received response 0x8000: b'00900049'
2020-11-12 17:19:59 DEBUG (ZiGate-Decode data) [zigate] RESPONSE 0x8000 - Status response : status:0, sequence:144, packet_type:73, error:b'', lqi:0
2020-11-12 17:19:59 DEBUG (ZiGate-Decode data) [zigate] Dispatch ZIGATE_RESPONSE_RECEIVED
2020-11-12 17:19:59 DEBUG (Thread-6) [zigate] STATUS code to command 0x0049:RESPONSE 0x8000 - Status response : status:0, sequence:144, packet_type:73, error:b'', lqi:0
2020-11-12 17:20:00 DEBUG (ZiGate-Listen) [zigate] Raw packet received, b'\x01\x02\x10M\x02\x10\x02\x1c\x9bYI\x02\x10\x12K\x02\x10"(\xf3\xea\x80\x02\x10\x03'
2020-11-12 17:20:00 DEBUG (ZiGate-Event Loop) [zigate] Dispatch ZIGATE_PACKET_RECEIVED
2020-11-12 17:20:00 DEBUG (ZiGate-Decode data) [zigate] Received response 0x004d: b'594900124b002228f3ea80'
2020-11-12 17:20:00 DEBUG (ZiGate-Decode data) [zigate] RESPONSE 0x004D - Device announce : addr:5949, ieee:00124b002228f3ea, mac_capability:10000000, lqi:0
2020-11-12 17:20:00 DEBUG (ZiGate-Decode data) [zigate] Device Announce RESPONSE 0x004D - Device announce : addr:5949, ieee:00124b002228f3ea, mac_capability:10000000, lqi:0
2020-11-12 17:20:00 DEBUG (ZiGate-Decode data) [zigate] Acquire Lock on device Device (5949) 00124b002228f3ea
2020-11-12 17:20:00 DEBUG (ZiGate-Decode data) [zigate] Release Lock on device Device (5949) 00124b002228f3ea
2020-11-12 17:20:00 DEBUG (ZiGate-Decode data) [zigate] Dispatch ZIGATE_DEVICE_UPDATED
2020-11-12 17:20:00 DEBUG (ZiGate-Decode data) [custom_components.zigate] Update device Device (5949) 00124b002228f3ea
2020-11-12 17:20:00 DEBUG (ZiGate-Decode data) [zigate] Dispatch ZIGATE_RESPONSE_RECEIVED
2020-11-12 17:20:00 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/zigate/__init__.py", line 807, in _handle_event
raise PlatformNotReady
homeassistant.exceptions.PlatformNotReady
2020-11-12 17:20:01 DEBUG (ZiGate-Listen) [zigate] Raw packet received, b'\x01\x02\x10M\x02\x10\x02\x1c\xeeYI\x02\x10\x12K\x02\x10"(\xf3\xea\x80u\x03\x01\x87\x02\x11\x02\x10\x02\x13\x85\x02\x10\x02\x10\x02\x10\x03'
2020-11-12 17:20:01 DEBUG (ZiGate-Event Loop) [zigate] Dispatch ZIGATE_PACKET_RECEIVED
2020-11-12 17:20:01 DEBUG (ZiGate-Decode data) [zigate] Received response 0x004d: b'594900124b002228f3ea80'
2020-11-12 17:20:01 DEBUG (ZiGate-Decode data) [zigate] RESPONSE 0x004D - Device announce : addr:5949, ieee:00124b002228f3ea, mac_capability:10000000, lqi:117
2020-11-12 17:20:01 DEBUG (ZiGate-Decode data) [zigate] Device Announce RESPONSE 0x004D - Device announce : addr:5949, ieee:00124b002228f3ea, mac_capability:10000000, lqi:117
2020-11-12 17:20:01 DEBUG (ZiGate-Decode data) [zigate] Acquire Lock on device Device (5949) 00124b002228f3ea
2020-11-12 17:20:01 DEBUG (ZiGate-Decode data) [zigate] Release Lock on device Device (5949) 00124b002228f3ea
2020-11-12 17:20:01 DEBUG (ZiGate-Decode data) [zigate] Dispatch ZIGATE_DEVICE_UPDATED
2020-11-12 17:20:01 DEBUG (ZiGate-Decode data) [custom_components.zigate] Update device Device (5949) 00124b002228f3ea
2020-11-12 17:20:01 DEBUG (ZiGate-Event Loop) [zigate] Dispatch ZIGATE_PACKET_RECEIVED
2020-11-12 17:20:01 DEBUG (ZiGate-Decode data) [zigate] Received response 0x8701: b'0000'
2020-11-12 17:20:01 DEBUG (ZiGate-Decode data) [zigate] RESPONSE 0x8701 - Route Discovery Confirmation : status:0, network_status:0, lqi:0
2020-11-12 17:20:01 DEBUG (ZiGate-Decode data) [zigate] Dispatch ZIGATE_RESPONSE_RECEIVED
2020-11-12 17:20:01 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/zigate/__init__.py", line 807, in _handle_event
raise PlatformNotReady
homeassistant.exceptions.PlatformNotReady
2020-11-12 17:20:01 DEBUG (ZiGate-Decode data) [zigate] Dispatch ZIGATE_RESPONSE_RECEIVED
2020-11-12 17:21:43 DEBUG (Thread-6) [zigate] discover_device 5949
2020-11-12 17:21:43 DEBUG (Thread-6) [zigate] no mac_capability
2020-11-12 17:21:43 DEBUG (Thread-6) [zigate] REQUEST : 0x0042 5949
2020-11-12 17:21:43 DEBUG (Thread-6) [zigate] Msg to send b'00420002505949'
2020-11-12 17:21:43 DEBUG (Thread-6) [zigate] Encoded Msg to send b'010210420210021250594903'
2020-11-12 17:21:43 DEBUG (Thread-6) [zigate] Waiting for status message for command 0x0042
2020-11-12 17:21:43 DEBUG (ZiGate-Listen) [zigate] Raw packet received, b'\x01\x80\x02\x10\x02\x10\x02\x15V\x02\x10\x91\x02\x10B\x02\x10\x03'
2020-11-12 17:21:43 DEBUG (ZiGate-Event Loop) [zigate] Dispatch ZIGATE_PACKET_RECEIVED
2020-11-12 17:21:43 DEBUG (ZiGate-Decode data) [zigate] Received response 0x8000: b'00910042'
2020-11-12 17:21:43 DEBUG (ZiGate-Decode data) [zigate] RESPONSE 0x8000 - Status response : status:0, sequence:145, packet_type:66, error:b'', lqi:0
2020-11-12 17:21:43 DEBUG (ZiGate-Decode data) [zigate] Dispatch ZIGATE_RESPONSE_RECEIVED
2020-11-12 17:21:43 DEBUG (Thread-6) [zigate] STATUS code to command 0x0042:RESPONSE 0x8000 - Status response : status:0, sequence:145, packet_type:66, error:b'', lqi:0
2020-11-12 17:22:22 DEBUG (Thread-10) [zigate] Auto saving /config/zigate.json
2020-11-12 17:22:22 DEBUG (Thread-10) [zigate] Saving persistent file
2020-11-12 17:22:22 DEBUG (Thread-10) [zigate] Acquire Lock to save persistent file
2020-11-12 17:22:22 DEBUG (Thread-10) [zigate] Release Lock of persistent file
2020-11-12 17:22:22 DEBUG (Thread-10) [zigate] REQUEST : 0x0010
2020-11-12 17:22:22 DEBUG (Thread-10) [zigate] Msg to send b'0010000010'
2020-11-12 17:22:22 DEBUG (Thread-10) [zigate] Encoded Msg to send b'01021010021002101003'
2020-11-12 17:22:22 DEBUG (Thread-10) [zigate] Waiting for status message for command 0x0010
2020-11-12 17:22:22 DEBUG (ZiGate-Listen) [zigate] Raw packet received, b'\x01\x80\x02\x10\x02\x10\x02\x15\x95\x02\x10\x02\x10\x02\x10\x10\x02\x10\x03\x01\x80\x10\x02\x10\x02\x15\x8f\x02\x10\x02\x13\x02\x13\x1a\x02\x10\x03'
2020-11-12 17:22:22 DEBUG (ZiGate-Event Loop) [zigate] Dispatch ZIGATE_PACKET_RECEIVED
2020-11-12 17:22:22 DEBUG (ZiGate-Decode data) [zigate] Received response 0x8000: b'00000010'
2020-11-12 17:22:22 DEBUG (ZiGate-Decode data) [zigate] RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:16, error:b'', lqi:0
2020-11-12 17:22:22 DEBUG (ZiGate-Decode data) [zigate] Dispatch ZIGATE_RESPONSE_RECEIVED
2020-11-12 17:22:22 DEBUG (ZiGate-Event Loop) [zigate] Dispatch ZIGATE_PACKET_RECEIVED
2020-11-12 17:22:22 DEBUG (ZiGate-Decode data) [zigate] Received response 0x8010: b'0003031a'
2020-11-12 17:22:22 DEBUG (ZiGate-Decode data) [zigate] RESPONSE 0x8010 - Version list : major:3, installer:31a, lqi:0, version:3.1a
2020-11-12 17:22:22 DEBUG (ZiGate-Decode data) [zigate] Dispatch ZIGATE_RESPONSE_RECEIVED
2020-11-12 17:22:22 DEBUG (Thread-10) [zigate] STATUS code to command 0x0010:RESPONSE 0x8000 - Status response : status:0, sequence:0, packet_type:16, error:b'', lqi:0

>

**Comment by orrionis** [comment]
Honnêtement je vois pas as quoi c'est due, pour info je sais qu'il fonctionne bien car sous ZHA il fonctionne bien mais je perd souvent la syncro, d'où mon basculement sur le plugin

**Comment by doudz** [comment]
Je ne vois rien d'anormal dans le log, il faudrait attendre un peu, peut-être. 
Pour info l'intégration avec zha a été amélioré , ça devrait fonctionner nettement mieux. Il faut attendre que HA inclue la version 0.7.0 de zigpy-zigate.

**Comment by orrionis** [comment]
Ok. 
Du coup mon capteur me sert pas trop

**Comment by orrionis** [comment]
J aibun soute pour le coup.  Peux etre mal installer votre plugin
Deja dois je installer zygpy en plus du package zigate home assistant 

Et dois je aussi copier le fichier package ?

**Comment by orrionis** [comment]
je viens de mettre a jour le firmware, et HA. mais coup il ne veut plus se connecter la zigate. 
il me reste plus que votre plugin qui fonctionne; mais j ai toujour pas mon capteur

**Comment by doudz** [comment]
Je recommande d'utiliser zha, l'intégration zigbee inclus dans Home Assistant.
Je vous conseille donc de supprimer ce plugin, relancer Home Assistant et d'ajouter l'Intégration zigbee depuis l'espace de configuration

**Comment by orrionis** [comment]
Oui c est ce que j ai fait, j ai UPGRADE le firmware en 3.1d 
Supprimer votre plugin. Installer l integration ZHA mais impossible de lier la zigate avec. 

Pourtant elle fonctionne bien car si je réinstalle votre plugin la elle apparaît et un de mes capteur xiaomi aqara apparait bien. Le sonoff lui toujour défaut. 

Pour résumer depuis la maj. ZHa ne veux plus reconnaître le PIZIGATE

**Comment by doudz** [comment]
quelle est la version de home assistant ? la dernière version 0.118.4 corrige un bug concernant la pizigate

**Comment by doudz** [comment]
Comment a été fait l'upgrade en 3.1d ? si c'est via le service du plugin alors ce n'est probablement pas le bon firmware car il y avait un bug qui est maintenant corrigé.
Si c'est le cas alors il faut refaire l'upgrade.

**Comment by orrionis** [comment]
J ai suivi un tuto officiel 
Il y a eu du changement j ai update en 0.118.4 mais j avais deja désinstallé ZHA
Et la plus moyen d installer ZHA ube erreur sur la libraire
Mais j avais fait un snapqhot avant la desinstall Donc retour en 0.117la tout fonctionne. Donc re maj en 0.118 et la retour de mon capteur aqara. Le sonoff pas encore...
A suivre donc

**Comment by 3mouchet** [comment]
> Je recommande d'utiliser zha, l'intégration zigbee inclus dans Home Assistant.
> Je vous conseille donc de supprimer ce plugin, relancer Home Assistant et d'ajouter l'Intégration zigbee depuis l'espace de configuration

Bonjour
Comment fait-on pour supprimer le plugin svp ?
