### ISSUE TITLE
ZIGATE_NOT_FOUND after power outage

### ISSUE THREAD

**Issue by b0kar** [doudz/homeassistant-zigate#156]
Hello,

I cannot get the zigate component to work anymore after my Nas was unplugged.
The zigate key was not affected by the power outage and is still working (I can send/receive commands) but not within home assistant.
I tried to reboot, stop/start zigate service, remove zigate.json.
None of the 3 above worked.

It already happened to me a few weeks ago and I can't remember how I managed to get it working again.

`Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/zigate/transport.py", line 221, in reconnect
self.serial = self.initSerial()
File "/usr/local/lib/python3.8/site-packages/zigate/transport.py", line 205, in initSerial
self._port = self._find_port(self._port)
File "/usr/local/lib/python3.8/site-packages/zigate/transport.py", line 261, in _find_port
return discover_port(port, self._search_re)
File "/usr/local/lib/python3.8/site-packages/zigate/transport.py", line 381, in discover_port
raise ZIGATE_NOT_FOUND('ZiGate not found')
zigate.transport.ZIGATE_NOT_FOUND: ZiGate not found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/zigate/__init__.py", line 392, in start_zigate
myzigate.autoStart(channel)
File "/usr/local/lib/python3.8/site-packages/zigate/core.py", line 414, in autoStart
self.startup(channel)
File "/usr/local/lib/python3.8/site-packages/zigate/core.py", line 431, in startup
self.setup_connection()
File "/usr/local/lib/python3.8/site-packages/zigate/core.py", line 309, in setup_connection
self.connection = ThreadSerialConnection(self, self._port)
File "/usr/local/lib/python3.8/site-packages/zigate/transport.py", line 198, in __init__
self.reconnect(False)
File "/usr/local/lib/python3.8/site-packages/zigate/transport.py", line 226, in reconnect
sys.exit(2)
SystemExit: 2`

**Comment by b0kar** [comment]
Not zigate related.
