### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by max5962** [doudz/homeassistant-zigate#33]
Hello @doudz,
i have some issues using the zigate in USB2 port ( many disconnect ) 
So i try to plug it in USB3 port.

The module seems to found and load the zigate, update zigate informations but do not create zigate devices :(
```
2019-02-05 17:23:09 DEBUG (SyncWorker_22) [zigate] Try loading persistent file
2019-02-05 17:23:09 DEBUG (SyncWorker_22) [zigate] Load success
2019-02-05 17:23:09 INFO (SyncWorker_22) [zigate] Searching ZiGate port
2019-02-05 17:23:09 ERROR (SyncWorker_26) [homeassistant.components.sensor.cert_expiry] Cannot connect to maxime-wantiez.ddns.net
2019-02-05 17:23:09 ERROR (SyncWorker_27) [homeassistant.components.feedreader] Error parsing feed https://vvvvvv.annuaire-telechargement.com/films-bluray-hd/rss.xml: <unknown>:65:65: undefined entity
2019-02-05 17:23:09 INFO (SyncWorker_22) [zigate] ZiGate found at /dev/ttyUSB0
2019-02-05 17:23:09 DEBUG (SyncWorker_22) [zigate] REQUEST : 0x0010
2019-02-05 17:23:09 DEBUG (SyncWorker_22) [zigate] Msg to send b'0010000010'
2019-02-05 17:23:09 DEBUG (SyncWorker_22) [zigate] Encoded Msg to send b'01021010021002101003'
2019-02-05 17:23:09 DEBUG (SyncWorker_22) [zigate] Waiting for status message for command 0x0010
2019-02-05 17:23:09 DEBUG (ZiGate-Listen) [zigate] Raw packet received, b'\x80\x02\x10\x02\x10\x02\x15\x95\x02\x10\x02\x10\x02\x10\x10\x02\x10\x03\x01\x80\x10\x02\x10\x02\x15\x9b\x02\x10\x02\x12\x02\x13\x02\x1f\x02\x10\x03'
2019-02-05 17:23:09 ERROR (ZiGate-Listen) [zigate] Malformed packet received, ignore it
2019-02-05 17:23:09 DEBUG (ZiGate-Event Loop) [zigate] Dispatch ZIGATE_PACKET_RECEIVED
2019-02-05 17:23:09 DEBUG (ZiGate-Decode data) [zigate] Received response 0x8010: b'0002030f'
2019-02-05 17:23:09 DEBUG (ZiGate-Decode data) [zigate] RESPONSE 0x8010 - Version list : major:2, installer:30f, rssi:0, version:3.0f
2019-02-05 17:23:09 DEBUG (ZiGate-Decode data) [zigate] Dispatch ZIGATE_RESPONSE_RECEIVED
2019-02-05 17:23:10 ERROR (SyncWorker_19) [custom_components.media_player.androidtv] Can't reach adb server, is it running ?
2019-02-05 17:23:10 WARNING (MainThread) [homeassistant.components.media_player] Platform androidtv not ready yet. Retrying in 60 seconds.
2019-02-05 17:23:12 WARNING (SyncWorker_22) [zigate] No response after command 0x0010 (1)
2019-02-05 17:23:12 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/zigate/__init__.py", line 279, in start_zigate
    myzigate.autoStart(channel)
  File "/config/deps/lib/python3.6/site-packages/zigate/core.py", line 323, in autoStart
    version = self.get_version()
  File "/config/deps/lib/python3.6/site-packages/zigate/core.py", line 739, in get_version
    self._version = self.send_data(0x0010, wait_response=0x8010).data
AttributeError: 'NoneType' object has no attribute 'data'
2019-02-05 17:23:13 WARNING (MainThread) [homeassistant.components.media_player] Platform cast not ready yet. Retrying in 60 seconds.
2019-02-05 17:23:36 DEBUG (ZiGate-Listen) [zigate] Raw packet received, b'\x01\x81\x02\x12\x02\x10*\xd3\xe9PX\x02\x11\x02\x10\x02\x10\xff\x02\x11\x02\x10B\x02\x10\x1d\x02\x11!\xc7\x02\x1b\x02\x13(\x1b\x02\x14!\xa8\x13\x02\x15!\x89\x02\x10\x02\x16$\x02\x11\x02\x10\x02\x10\x02\x10\x02\x10\x02\x1a!\x02\x10\x02\x10d\x10\x02\x10\xa8\x03'
2019-02-05 17:23:36 DEBUG (ZiGate-Event Loop) [zigate] Dispatch ZIGATE_PACKET_RECEIVED
2019-02-05 17:23:36 DEBUG (ZiGate-Decode data) [zigate] Received response 0x8102: b'e95058010000ff010042001d0121c70b03281b0421a81305218900062401000000000a210000641000'
2019-02-05 17:23:36 DEBUG (ZiGate-Decode data) [zigate] RESPONSE 0x8102 - Individual Attribute Report : sequence:233, addr:5058, endpoint:1, cluster:0, attribute:65281, status:0, data_type:66, size:29, data:0121c70b03281b0421a81305218900062401000000000a210000641000, rssi:168
```

![test](https://user-images.githubusercontent.com/34659571/52287886-5244f080-296b-11e9-96b0-0963927276ca.png)

**Comment by max5962** [comment]
hello @doudz 
after doing some tests
bind and unbind the USB : 
echo "3-1" > /sys/bus/usb/drivers/usb/unbind
echo "3-1" > /sys/bus/usb/drivers/usb/bind

seems working.

**Comment by doudz** [comment]
the problem was a malformed packet received during asking for zigate firmware version
