### ISSUE TITLE
first start of component error

### ISSUE THREAD

**Issue by biau** [doudz/homeassistant-zigate#39]
I've just found that since 0.88 deps are located in python3.7 previously was 3.6.
So hass need to download the lib again and I had an error at the first run. Restarting hass solved the issue.
So now I've completely delete my deps directory and the error is happening again at first start:

2019-02-25 15:08:11 INFO (SyncWorker_5) [homeassistant.util.package] Attempting install of zigate==0.28.1
2019-02-25 15:08:12 INFO (MainThread) [homeassistant.setup] Setup of domain weather took 0.8 seconds.
2019-02-25 15:08:16 INFO (MainThread) [homeassistant.setup] Setting up zigate
2019-02-25 15:08:16 INFO (MainThread) [homeassistant.setup] Setting up tts
2019-02-25 15:08:16 INFO (MainThread) [homeassistant.setup] Setting up cloud
2019-02-25 15:08:16 INFO (MainThread) [homeassistant.setup] Setup of domain cloud took 0.0 seconds.
2019-02-25 15:08:16 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.kodi
2019-02-25 15:08:16 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.kodi
2019-02-25 15:08:16 ERROR (MainThread) [homeassistant.setup] Error during setup of component zigate
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/setup.py", line 154, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/zigate/__init__.py", line 137, in setup
    import zigate
ModuleNotFoundError: No module named 'zigate'

Just FYI because as before a restart of hass solve the issue.

**Comment by doudz** [comment]
not sure why but I got the same at the same time, I suppose a network problem

**Comment by biau** [comment]
mmh I've been playing with the deps directory because wanted to try your dev branch and every single time hass restart with an empty deps directory zigate is not working and need a restart of hass.

**Comment by biau** [comment]
I've deleted my deps directory one more time before upgrading to versino 0.29 of your library and you were right it works at first try this time.
So it looks like it was a network issue
