### ISSUE TITLE
Eurotronic Thermostat

### ISSUE THREAD

**Issue by cgradl** [doudz/homeassistant-zigate#86]
Hello doudz
Error description:
Paired 2 Eurotronic Spirit Thermostats
Zigbee entity is showing up
once verz shortly a climate entity and thermostat demand entity was showing up but disappeared shortly after
repairing/discover or similar activity gave no change
log file is spammed with the following error:
```
2019-12-08 23:07:14 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 408, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 275, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 309, in _async_write_ha_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 175, in state
    return self.hvac_mode
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 278, in hvac_mode
    raise NotImplementedError()
NotImplementedError
```

zigate entity attributes:
`

zigate.00158d0001ffc686 | 2019-12-09 23:42:34 | lqi_percent: 47 type: SPZB0001 manufacturer: Eurotronic receiver_on_when_idle: false missing: false generic_type:  discovery: auto-discovered groups: {} datecode: null battery_voltage: null battery_level: 100 addr: a666 ieee: 00158d0001ffc686 last_seen: 2019-12-09 23:42:34 lqi: 120 mac_capability: 10000000 friendly_name: Eurotronic SPZB0001 (a666) 00158d0001ffc686 icon: mdi:access-point
-- | -- | --

template json:
```
{
    "endpoints": [
        {
            "clusters": [
                {
                    "attributes": [
                        {
                            "attribute": 8
                        },
                        {
                            "attribute": 16386
                        },
                        {
                            "attribute": 16392
                        },
                        {
                            "attribute": 16387
                        },
                        {
                            "attribute": 0
                        },
                        {
                            "attribute": 18
                        },
                        {
                            "attribute": 20
                        }
                    ],
                    "cluster": 513
                },
                {
                    "attributes": [
                        {
                            "attribute": 4,
                            "data": "Eurotronic"
                        },
                        {
                            "attribute": 5,
                            "data": "SPZB0001"
                        }
                    ],
                    "cluster": 0
                }
            ],
            "device": 769,
            "endpoint": 1,
            "in_clusters": [
                0,
                1,
                3,
                513,
                25,
                10
            ],
            "out_clusters": [
                0,
                1,
                3,
                4,
                513,
                25,
                10
            ],
            "profile": 260
        }
    ],
    "generictype": "",
    "info": {
        "mac_capability": "10000000",
        "power_type": 0
    }
}

````
json from zigate.json
```
 {
            "addr": "a666",
            "discovery": "auto-discovered",
            "endpoints": [
                {
                    "clusters": [
                        {
                            "attributes": [
                                {
                                    "attribute": 8,
                                    "data": 108,
                                    "name": "heating_demand",
                                    "value": 108
                                },
                                {
                                    "attribute": 0,
                                    "data": 2000,
                                    "name": "local_temperature",
                                    "type": "float",
                                    "unit": "\u00b0C",
                                    "value": 20.0
                                },
                                {
                                    "attribute": 18,
                                    "data": 2100,
                                    "name": "occupied_heating_setpoint",
                                    "type": "float",
                                    "unit": "\u00b0C",
                                    "value": 21.0
                                },
                                {
                                    "attribute": 20,
                                    "data": 1600,
                                    "name": "unoccupied_heating_setpoint",
                                    "type": "float",
                                    "unit": "\u00b0C",
                                    "value": 16.0
                                },
                                {
                                    "attribute": 16387,
                                    "data": 2100
                                }
                            ],
                            "cluster": 513
                        },
                        {
                            "attributes": [
                                {
                                    "attribute": 4,
                                    "data": "Eurotronic",
                                    "name": "manufacturer",
                                    "value": "Eurotronic"
                                },
                                {
                                    "attribute": 5,
                                    "data": "SPZB0001",
                                    "name": "type",
                                    "type": "str",
                                    "value": "SPZB0001"
                                }
                            ],
                            "cluster": 0
                        }
                    ],
                    "device": 769,
                    "endpoint": 1,
                    "in_clusters": [
                        0,
                        1,
                        3,
                        513,
                        25,
                        10
                    ],
                    "out_clusters": [
                        0,
                        1,
                        3,
                        4,
                        513,
                        25,
                        10
                    ],
                    "profile": 260
                }
            ],
            "generictype": "",
            "info": {
                "addr": "a666",
                "ieee": "00158d0001ffc686",
                "last_seen": "2019-12-09 23:42:46",
                "lqi": 123,
                "mac_capability": "10000000"
            }
        },
```

I can not figure out how to make the climate and other entities show up.
Is there anything else you would need to have a look into this?

**Comment by cgradl** [comment]
thanks for fast reaction! will test and report as soon as possible

**Comment by cgradl** [comment]
I finally was able to test.
Works now like a charm!

big thanks!
