### ISSUE TITLE
"Error: 500 Internal Server Error" Since last update via Hacs

### ISSUE THREAD

**Issue by medaemon** [doudz/homeassistant-zigate#88]
Hello,

I have updated today the zigate component from HACS but I now have the follwoing error message in the Zigate Page :
```
Error: 500 Internal Server Error
Sorry, the requested URL 'http://localhost:9998/' caused an error:

Internal Server Error
```

I have double check my config yaml : 
```
zigate:
  host: 192.168.1.99:9999
  admin_panel: true
```

(I have a wifi zigate, zigate is on 3.1a firmware)

Any help on where to check, I have no idea from where the localhost:9998 comes from perhaps py code of the component...

![image](https://user-images.githubusercontent.com/54717813/71174433-78167380-2265-11ea-8619-55d6c78ec76e.png)

**Comment by medaemon** [comment]
Hello doudz,
I saw your very quick fix, but unfortunatly it does not seems to fix my issue I still have the same issue.
I have first Upgraded with the version of fix, same behavior.
As it does not changes I reinstall completely, same behavior.

**Comment by doudz** [comment]
Did you to push CTRL+F5

**Comment by pdecat** [comment]
Same issue here, will test the fix.

**Comment by medaemon** [comment]
Yes, I have refreshed with Ctrl+F5 several times and even test on another browser (sometime caches does not help ^^)

**Comment by pdecat** [comment]
Still the same issue:

```
<zigate.core.ZiGate object at 0x7fe6d5ca4ad0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/lib/python3.7/site-packages/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/bottle.py", line 3650, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/zigate/adminpanel/__init__.py", line 55, in index
    'model': zigate_instance.model
  File "/usr/local/lib/python3.7/site-packages/zigate/core.py", line 219, in model
    if self.connection.vid_pid() == (0x0403, 0x6001):
  File "/usr/local/lib/python3.7/site-packages/zigate/transport.py", line 210, in vid_pid
    port = list(serial.tools.list_ports.grep(self.serial.port))[0]
IndexError: list index out of range
<zigate.core.ZiGate object at 0x7fe6d5ca4ad0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/lib/python3.7/site-packages/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/bottle.py", line 3650, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/zigate/adminpanel/__init__.py", line 55, in index
    'model': zigate_instance.model
  File "/usr/local/lib/python3.7/site-packages/zigate/core.py", line 219, in model
    if self.connection.vid_pid() == (0x0403, 0x6001):
  File "/usr/local/lib/python3.7/site-packages/zigate/transport.py", line 210, in vid_pid
    port = list(serial.tools.list_ports.grep(self.serial.port))[0]
IndexError: list index out of range
```

Pressing Ctrl-Shift-F5 does help either.

**Comment by doudz** [comment]
Ok I see. Thanks for traceback

**Comment by medaemon** [comment]
I'm probably unlucky but does not change the status for me...
Can I help you with some traces ? (don't know how to provide you the same traceback as pdecat did)

**Comment by pdecat** [comment]
Fixed the issue for me, thanks @doudz! 

![image](https://user-images.githubusercontent.com/318490/71180993-908d8a80-2273-11ea-8532-daf6de28ebd0.png)
