### ISSUE TITLE
Failed to start network

### ISSUE THREAD

**Issue by Uneo7** [doudz/homeassistant-zigate#96]
Bonjour,

J'ai recement aquis un zigate USB que j'essaye de faire marcher avec ce composant mais malheureusement, je n'y parviens pas.

J'ai installé le composant à l'aide de hacs et configuré le module de la manière suivante : 
```
zigate:
  admin_panel: true
```

Capdant peut de temps après le lance de home assistant, cette erreur apparait des les logs : 

```
2020-01-21 02:18:51 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 214, in async_setup_platform
    self.hass, self.config, self.domain, platform_type
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 229, in async_prepare_setup_platform
    integration = await loader.async_get_integration(hass, platform_name)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 311, in async_get_integration
    Integration.resolve_from_root, hass, components, domain
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 154, in resolve_from_root
    manifest_path = pathlib.Path(base) / domain / "manifest.json"
  File "/usr/lib/python3.7/pathlib.py", line 901, in __truediv__
    return self._make_child((key,))
  File "/usr/lib/python3.7/pathlib.py", line 688, in _make_child
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.7/pathlib.py", line 642, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
2020-01-21 02:18:53 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry configuration.yaml for zigate
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config_entries.py", line 214, in async_setup
    result = await component.async_setup_entry(  # type: ignore
AttributeError: module 'custom_components.zigate' has no attribute 'async_setup_entry'
```

Suivi de près par :
```
2020-01-21 02:19:16 ERROR (SyncWorker_16) [zigate] Failed to start network
```

De surcroît, lorsque j'essaye de passer la zigate en permit join via la paneau administrateur, celui ci me retourne un 404.

```
Error: 404 Not Found

Sorry, the requested URL 'http://localhost:9998/zigateproxy/?_=1579573500.0931175' caused an error:

Not found: '/zigateproxy/'
```

Ai-je manqué une étape de configuration ? (à noter que la zigate et bien à jour et fonctionelle)

En vous remerciant par avance,
Baptiste

**Comment by Uneo7** [comment]
Les informations de la zigate retournées par le panel admin : 

| Attribute        | Value  |
|------------------|--------|
| Lib version      | 0.38.2 |
| Port             | auto   |
| Connected        | True   |
| Firmware version | 3.1a   |
| Model            | TTL    |

**Comment by guirem** [comment]
Hi,

Same here. 
This is the first time I try to install this component so I don't know if it worked before.

Home Assistant version 0.104.2

Lib version: 0.38.2
Port: /dev/ttyUSB0
Connected | True
Firmware version: 3.1b
Model: TTL

**Comment by doudz** [comment]
L'erreur `AttributeError: module 'custom_components.zigate' has no attribute 'async_setup_entry'
` peut être ignoré, ça n'a aucune incidence sur le fonctionnement

**Comment by doudz** [comment]
C'est corrigé

**Comment by Uneo7** [comment]
Bonjour,

Merci pour ce patch rapide, je constate en effet que le panel admin marche comme prévu. 
Cendant, je ne parviens toujours pas à utiliser le module correctement.

En effet, je ne peut apprairer aucun appareil. J'ai essayé 3 lampes ika des cpateurs xiaomi et des prises osram rien n'y fait.

Je vous bien la zigate clignoter en bleu pour indiqer son passage en permit join mais c'est tout ce qu'il se passe.

Dans le logs je constate les erreurs suivantes : 

```
2020-01-21 12:07:13 ERROR (SyncWorker_7) [zigate] Failed to start network
```
puis
```
2020-01-21 12:13:17 ERROR (ZiGate-Decode data) [zigate] Command 0x004e failed Failed (ZigBee event codes) 0x80 : b''
2020-01-21 12:13:22 WARNING (Thread-3) [zigate] No response waiting command 0x804e
2020-01-21 12:13:22 ERROR (Thread-3) [zigate] Failed to build neighbours table
```

**Comment by doudz** [comment]
Le problème vient sans doute d'ici : `Failed to start network`
Il faudrait essayer de faire un erase PDM, en envoyant la commande 0x0012 via le service zigate.raw_command

**Comment by Uneo7** [comment]
Bonjour,

```
A new ZiGate device "Device (02b0) 00158d00035a4eeb" has been added !
```

En effet, ça fonctionne :smile: un grand merci pour votre aide.
